[package]
name = "conda-deny"
description = "A CLI tool to check your project's dependencies for license compliance."
version = "0.3.2"
edition = "2021"

[features]
default = ["native-tls"]
native-tls = [
    "reqwest/native-tls",
    "reqwest/native-tls-alpn",
]
rustls-tls = [
    "reqwest/rustls-tls",
    "reqwest/rustls-tls-native-roots",
]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.5", features = ["derive"] }
serde = { version = "1.0.214", features = ["derive"] }
serde_json = "1.0.132"
toml = "0.8.19"
tokio = { version = "1.41.0", features = ["full"] }
reqwest = { version = "0.12.9", default-features = false, features = ["http2"] }
serde_yaml = "0.9.34"
regex = "1.11.1"
spdx = "0.10.6"
colored = "2.1.0"
async-trait = "0.1.83"
rattler_conda_types = "0.28.3"
rattler_lock = "0.22.28"
anyhow = "1.0.92"
clap-verbosity-flag = "2.2.2"
env_logger = "0.11.5"
log = "0.4.22"

[dev-dependencies]
assert_cmd = "2.0.14"
predicates = "3.1.0"
serial_test = "3.1.1"
