[package]
name = "conda-deny"
description = "A CLI tool to check your project's dependencies for license compliance."
version = "0.3.1"
edition = "2021"

[features]
default = ["native-tls"]
native-tls = [
    "reqwest/native-tls",
    "reqwest/native-tls-alpn",
]
rustls-tls = [
    "reqwest/rustls-tls",
    "reqwest/rustls-tls-native-roots",
]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.5", features = ["derive"] }
serde = { version = "1.0.211", features = ["derive"] }
serde_json = "1.0.132"
toml = "0.8.19"
tokio = { version = "1.36.0", features = ["full"] }
reqwest = { version = "0.12.8", default-features = false, features = ["http2", "blocking"] }
serde_yaml = "0.9.34"
regex = "1.11.0"
spdx = "0.10.6"
colored = "2.1.0"
async-trait = "0.1.83"
rattler_conda_types = "0.28.2"
rattler_lock = "0.22.27"
anyhow = "1.0.90"
clap-verbosity-flag = "2.2.2"
env_logger = "0.11.5"
log = "0.4.22"
tar = "0.4.42"
zip = "2.2.0"
zstd = "0.13.2"
bzip2 = "0.4.4"

[dev-dependencies]
assert_cmd = "2.0.14"
predicates = "3.1.0"
serial_test = "3.1.1"
